CREATE TABLE public.conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid(), title text NOT NULL DEFAULT 'New conversation', messages jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.conversations TO authenticated;
GRANT ALL ON public.conversations TO service_role;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their conversations" ON public.conversations FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE INDEX conversations_owner ON public.conversations(user_id, updated_at DESC);
CREATE TABLE public.saved_plans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid(), title text NOT NULL, plan jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.saved_plans TO authenticated;
GRANT ALL ON public.saved_plans TO service_role;
ALTER TABLE public.saved_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their plans" ON public.saved_plans FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE INDEX plans_owner ON public.saved_plans(user_id);
CREATE TABLE public.contact_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), full_name text NOT NULL, business_name text NOT NULL, email text NOT NULL, phone text, website_type text NOT NULL, budget text, description text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT INSERT ON public.contact_requests TO anon, authenticated;
GRANT ALL ON public.contact_requests TO service_role;
ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Visitors submit enquiries" ON public.contact_requests FOR INSERT TO anon, authenticated WITH CHECK (length(full_name) BETWEEN 2 AND 200 AND length(business_name) BETWEEN 1 AND 200 AND length(email) BETWEEN 3 AND 320 AND length(description) BETWEEN 10 AND 10000);
CREATE TABLE public.ai_access_state (id text PRIMARY KEY, blocked boolean NOT NULL DEFAULT false, reason text, status integer, updated_at timestamptz NOT NULL DEFAULT now());
GRANT ALL ON public.ai_access_state TO service_role;
ALTER TABLE public.ai_access_state ENABLE ROW LEVEL SECURITY;